---
name: Checks

on: [push, pull_request]

jobs:
  test-lint:
    name: Test and test-lint
    runs-on: ubuntu-latest
    steps:
      - name: Login to Dokcer Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test
        run: docker compose run --rm app sh -c "python manage.py test"
      - name: Linting
        run: docker compose run --rm app sh -c "flake8"
      

